language: objective-c
# osx_image: xcode9.1
# xcode_scheme: YAPI
# xcode_workspace: YAPI.xcworkspace
# script: set -o pipefail && xcodebuild test -workspace YAPI.xcworkspace -scheme YAPI -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace YAPI.xcworkspace -scheme YAPIV3 CODE_SIGNING_REQUIRED=NO
